version: '2'
services:
  db:
    container_name: db
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
    - "./db:/docker-entrypoint-initdb.d"
  web:
    container_name: web
    build: "./web"
    ports:
    - 8080:8080
    depends_on:
      - db
